print("###########################")
print("#                         #")
print("#   Mario Franca Wijaya   #")
print("#     2210817310009       #")
print("#                         #")
print("###########################")
